name: Ensure that Release builds are not broken

on:
  push:
    branches: [ v2_release, v2_develop ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ v2_release, v2_develop ]
    paths-ignore:
      - '**.md'
      
jobs:
  build_release:
    # Ensure that RELEASE builds are not broken
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        dotnet-quality: 'ga'

    - name: Build Release Terminal.Gui
      run: dotnet build Terminal.Gui/Terminal.Gui.csproj --configuration Release

    - name: Pack Release Terminal.Gui
      run: dotnet pack Terminal.Gui/Terminal.Gui.csproj --configuration Release --output ./local_packages

    - name: Build Release Solution
      run: dotnet build --configuration Release
